[Pure Storage FA Agent] Add UserAgent string
Checkmk/checkmk pull request #616
Opened 2023-08-04 01:07 UTC by sdodsley

## General information

Pure Storage monitors 3rd party integrations that access API endpoints through dial-home technology.
The preferred way of doing this is to provide a `User-Agent` string.

Proposer is Director of Open Source Integrations at Pure Storage

## Proposed changes

Add a `User-Agent` string in the API call header.

2023-08-04 03:34 UTC, sdodsley commented
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

2023-10-22 21:03 UTC, mo-ki requested changes
Hi Simon,
Thanks for your interest and PR! A small change and we can merge this.

2023-10-22 21:03 UTC, mo-ki commented on cmk/special_agents/agent_pure_storage_fa.py
> +__version__ = "1.0.0"
The version should match the Checmk version that ships this agent, `"2.3.0b1"` in this case. It will be automatically updated to always match.

2023-10-23 11:30 UTC, mo-ki commented
Ah, sorry. I just realized that's what you did in your earlier commit. I'll merge that then!
Thanks again!

2023-10-24 07:13 UTC, closed without merging