Upstream PR for all bugfixes since first commit of Nutanix Prism checks
Checkmk/checkmk pull request #638
Opened 2023-10-15 09:04 UTC by Yogibaer75

This PR request includes two bug fixes and 1 missing check for Nutanix.

Missing checks - host network interfaces
Bug fixes 
- vm memory -> unknown if no memory values existing fixed
- vm_tools -> state can be ignored

2023-10-15 09:05 UTC, Yogibaer75 commented
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

2023-10-24 08:13 UTC, martinhv commented
From a PM perspective, I approve this change. It creates value for Checkmk and fixes bugs. 
The technical evaluation I leave to dev.

2023-10-24 12:55 UTC, BenediktSeidl requested changes
Thank you very much for your contribution. In general, it looks good, it even has tests :heart: very nice!

To merge I would add three (or two) werks, but I need some more context to the following items:
* vm memory -> unknown if no memory values existing fixed
* vm_tools -> state can be ignored
It would be good to know what the previous behavior was, and how it was fixed, so I can come up with a Werk that other customers can understand.

Can you split your two commits into three commits? Two commits for the two fixes and an additional commit for the new feature.

You can add the style change in `cmk/base/plugins/agent_based/prism_cluster_io.py` to any of these commits, but it would be cool if you could mention it in the commit message.

This probably seems overly picky, but git history is often the only way to understand the intent of changes from years ago, so we try to maintain it as best we can.

I've also left four code annotations with questions and comments, I'm open to discussiong these issues.

2023-10-24 12:55 UTC, BenediktSeidl commented on cmk/base/plugins/agent_based/prism_host_networks.py
> +    data = section.get(item)
are you sure that those statements are really needed?
i would think that this case is already handled by `interfaces.check_multiple_interfaces`.

2023-10-25 08:34 UTC, Yogibaer75 commented on cmk/base/plugins/agent_based/prism_host_networks.py
> +def _create_interface(section: Section) -> interfaces.Section[interfaces.InterfaceWithRates]:
I must added this workaround to make tests working. I copied this part from one of your own checks :)

2023-10-25 17:56 UTC, Yogibaer75 commented on cmk/base/plugins/agent_based/prism_host_networks.py
> +# -*- encoding: utf-8; py-indent-offset: 4 -*-
Why is this now a problem in all the other checks made before there is the same header?

2023-10-25 18:07 UTC, Yogibaer75 commented on cmk/base/plugins/agent_based/utils/prism.py
> +def load_json2(string_table: StringTable) -> PrismAPIData2:
PrismApiData --> dict[str, Any]
PrismApiData2 --> dict[dict, Any]
Again this extra code was only made to make the testing and checks happy.

2023-10-25 18:15 UTC, Yogibaer75 commented
> * vm memory -> unknown if no memory values existing fixed
It is possible the one defined VM don't report a memory value and then the check was crashing if no value exists.

> * vm_tools -> state can be ignored
>   It would be good to know what the previous behavior was, and how it was fixed, so I can come up with a Werk that other customers can understand.
Before you needed to specify a wanted state. If nothing was specified the default parameter state was used. Now you can define to ignore the state what can be helpful for machines where no tools can be installed like appliances and so on.

> Can you split your two commits into three commits? Two commits for the two fixes and an additional commit for the new feature.
After the submit no, I don't know how to split the commits.

> You can add the style change in `cmk/base/plugins/agent_based/prism_cluster_io.py` to any of these commits, but it would be cool if you could mention it in the commit message.

Ok that's a point. As this was a commit of all the collected changes from my repo it is possible that i forgot to mention.

> This probably seems overly picky, but git history is often the only way to understand the intent of changes from years ago, so we try to maintain it as best we can.
> 
> I've also left four code annotations with questions and comments, I'm open to discussiong these issues.
I wrote some comments. All these "problems" are only there as your tests wanted these changes. Before my simple code was rejected from the mypy/pytest tests 🤣 

I think some constructs are over complicated inside CMK if you want to make the test environment happy.
Later bugfixes a can submit as simple small PRs, but then we also need a better way for the processing of these PRs.

2023-10-26 13:23 UTC, BenediktSeidl commented
Thanks for your response and the additional info about your change. We are happy that you share your domain knowledge with checkmk and want to include this in our product.
I would suggest, that I take over from here, adapt your code to meet our coding standards, split it into three commits and add the necessary werks. The business logic will not be altered. You are still the main author of the git commits, to show that there were additional changes, I would add myself as a co-author.
Is this okay for you?

2023-10-26 13:24 UTC, BenediktSeidl commented on cmk/base/plugins/agent_based/prism_host_networks.py
> +# -*- encoding: utf-8; py-indent-offset: 4 -*-
before asking you to change this, i asked internally and the official statement is, that we should only use the checkmk license header.
your files were the only exception that used non-official license headers. our license header check was very lax in this regard. today i merged a change which applies stricter rules from now on.

2023-10-26 15:22 UTC, Yogibaer75 commented
> Is this okay for you?

Yes why not :)

2023-11-02 05:57 UTC, BenediktSeidl commented on cmk/base/plugins/agent_based/utils/prism.py
> +def load_json2(string_table: StringTable) -> PrismAPIData2:
ah! now i see the difference, sorry about this.

2023-11-09 07:06 UTC, BenediktSeidl commented
@Yogibaer75 yesterday i merged a first version of your change into the master branch. can you please check in a daily master build if it is working as intended? i've implemented some bigger changes for parsing the json file, as it was suggested in the internal code review.

the internal code review also opened the question if the api already returns rates, or if those are global counters? as far as i understand those are rates based on a 30 seconds interval. is the comment i added correct? https://github.com/Checkmk/checkmk/blob/b9f640b864f2b284d0bb33efbf095471929da339/cmk/base/plugins/agent_based/prism_host_networks.py#L78-L80 

thanks again for your contribution!

2023-11-09 10:12 UTC, Yogibaer75 commented
> the internal code review also opened the question if the api already returns rates, or if those are global counters? as far as i understand those are rates based on a 30 seconds interval. is the comment i added correct?
> 
Yes these are already rates and no counters. And the rate is based on the last 30 seconds. I found no other way than this to get the interface data.

For the master build i must check the next days if it does what it should :)

2023-11-24 07:48 UTC, closed without merging