refactors agent_cisco_meraki
Checkmk/checkmk pull request #654
Opened 2023-12-12 18:52 UTC by thl-cmk

This is the first step towards the improving of the agent. For now there are no changes visible from the outside. This moves all API requests to a class hirachie based in the DataCache class. The API cache is not yet active.

Nexts steps:
- streamlining usage of "id" versus "id_"
- change the logic from include sections to exclude sections
- activate the API cache (with option to disable via wato)
- option to use the organisation id as host prefix

2024-03-14 14:55 UTC, si-23 requested changes
Thank you for the patch. The basic idea seems to be useful.

Please implement functionalities if and only if they are really needed.
Please divide your change into smaller commits. It's easier to review.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +            MerakiOrganisation(config=config, organisation=organisation)
key-worded args are not necessary because config and organisation are distinguishable by default.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +    organisations = [
the idea of configured IDs is the following:

- If you configure IDs then - for these IDs - data is fetched (from API or from cache) to enrich the organisation data
- If not then collect all IDs (from API or from cache)

Here you mix up these two concepts.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +    use_cache: bool = False
Do not implement functionalities which are not used.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +    def name(self):
Do not implement functionalities which are not used.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +class MerakiGetOrganization(MerakiSectionOrg):
Do not implement classes which are not used.

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +            for device_status in MerakiGetOrganizationDevicesStatuses(
The initialization of this (and the following) classes can be moved to the init function (composite).

2024-03-14 14:55 UTC, si-23 commented on cmk/special_agents/agent_cisco_meraki.py
> +from typing import Any, Final
Avoid "Any": from a typing perspective all consumer actions are OK/allowed (which is very bad).
You can use object instead.

2024-06-19 06:50 UTC, closed without merging

2024-06-19 08:14 UTC, TimotheusBachinger commented
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

2024-06-19 13:44 UTC, TimotheusBachinger commented
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.